<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= service('assets')->getHeaderHtml(); ?>
</head>
<body>
<div id="site-wrap">
    <div id="site-container">
        <div id="<?= service('app')->getFullActionName(); ?>">
            <header id="header">
            </header>
            <div id="main">
            </div>
            <footer id="footer">
            </footer>
        </div>
    </div>
</div>
<section id="docklet-ow">
    <!--chat list-->
</section>
<a role="button" id="scrolltop" class="fade" ride="scrollToTop"></a>
<input type="hidden" id="dirty" value="0"/>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
</body>
</html>