<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= service('html_header')->getHtml(); ?>
</head>
<body>
<div class="site-wrap">
    <div class="site-container <?= service('app')->getFullActionName(); ?>">
        <header>
            <section>
                <div class="container">

                </div>
            </section>
        </header>
        <section>
            <div class="container">

            </div>
        </section>
        <footer>
            <section>
                <div class="container">

                </div>
            </section>
        </footer>
    </div>
</div>
<section id="docklet">
    <!--chat list-->
</section>
<a role="button" id="scrolltop" class="fade" ride="scrollToTop"></a>
<input type="hidden" id="dirty" value="0"/>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
</body>
</html>