<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--    --><? //= service('html')->getHtml(); ?>
</head>
<body>
<? //= $this->partial('layout/master/header'); ?>
<? //= $this->partial('layout/master/content'); ?>
<? //= $this->partial('layout/master/footer'); ?>
<section id="docklet">
    <!--chat list-->
</section>
<a role="button" id="scrolltop" class="fade" ride="scrollToTop"></a>
<input type="hidden" id="dirty" value="0"/>
<? //= service('html_footer')->getHtml() ?>
</body>
</html>