<footer>
    <section class="cross-bar">
        <div class="container">
            <div class="row">
                <div class="col-md-5 text-left">
                    <a href="#">&copy; YouNet Company 2016, Alright reversed.</a>
                </div>
                <div class="col-md-7 text-right">
                    <a href="#">Privacy</a>
                    <a href="#">Site Map</a>
                    <a href="#">Videos</a>
                    <a href="#">Library</a>
                    <a href="#">Feedback</a>
                </div>
            </div>
        </div>
    </section>
    <section class="large-board">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h3>LOREM IPSUM IS SIMPLY DUMMY</h3>
                    <p>
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown priggggg s kkk heets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
                    </p>
                </div>
                <div class="col-md-3">
                    <h3>LOREM IPSUM</h3>
                    <ul>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                    </ul>
                </div>
                <div class="col-md-3 text-right">
                    <h3>LOREM IPSUM</h3>
                    <ul>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                        <li><a href="#">Sample link</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</footer>